name: run tests
on:
  push:
    branches:
      - main
jobs:
  run_java_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: chmod +x gradlew
      - run: chmod +x gradle/wrapper/gradle-wrapper.jar

      - uses: docker/setup-buildx-action@v1.6.0

      - name: Start containers
        working-directory: ./test_suite
        run: docker-compose up -d
        
      - run: sleep 30

      - name: Start tests
        run: ./gradlew jvmtest

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: build/test-results/jvmTest/*.xml



